### ISSUE TITLE
Windows: go get -error while installing u2fhid

### ISSUE THREAD

**Issue by netmiller** [flynn/u2f#3]
I managed to build working test-prog in my OsX-env, but had some errors building it for Windows.

Then installed MinGW-64 (v.5.0.3 64bit) in my Windows 10 env.
But I got errors when installing dependencies (github.com/flynn/u2f/u2fhid) :

````
PS C:\Users\esa\devel\u2f> go get github.com/flynn/u2f/u2fhid

# github.com/flynn/hid
src\github.com\flynn\hid\hid_windows.go:194: cannot use C.DWORD(unsafe.Sizeof(attrs)) (type C.DWORD) as type C.ULONG in assignment
````

gcc is in version: 

````
PS C:\Users\esa\devel\u2f> gcc --version
gcc.exe (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 7.2.0
````

Any glue for fixing this ???? 
I think I need some help because I have not C or C++ background, Go is my favourite still :)

**Comment by netmiller** [comment]
I can live this if I can build win-executable on my Mac (osx), but I got this error :

````
► iMac@u2f$ GOOS=windows GOARCH=amd64 go build -o yubitest64.exe t1.go

# github.com/flynn/u2f/u2fhid
src/github.com/flynn/u2f/u2fhid/hid.go:52:18: undefined: hid.Devices
src/github.com/flynn/u2f/u2fhid/hid.go:69:21: info.Open undefined (type *hid.DeviceInfo has no field or method Open)
````

and same with `386`arch :

````
► iMac@u2f$ GOOS=windows GOARCH=386 go build -o t1.exe t1.go
# github.com/flynn/u2f/u2fhid
src/github.com/flynn/u2f/u2fhid/hid.go:52:18: undefined: hid.Devices
src/github.com/flynn/u2f/u2fhid/hid.go:69:21: info.Open undefined (type *hid.DeviceInfo has no field or method Open)
````

when  running `go run` or building for darwin, it's working like charm :

````
► iMac@u2f$ go build -o testyubi t1.go
► iMac@u2f$ ./testyubi
````

Anyone who can advise; obviously it has something to do with __hid.go / hid_windows.go__.
Is there any workaround??

**Comment by netmiller** [comment]
OK, some progress in Windows: installed tdm64-gcc-5.1.0-2 , and dependencies will now install.

Still some problems when running test-prog, but I will try to find it within my code.

**Comment by CharlieAIO** [comment]
> OK, some progress in Windows: installed tdm64-gcc-5.1.0-2 , and dependencies will now install.
> 
> Still some problems when running test-prog, but I will try to find it within my code.

Hi @netmiller did you ever find a solution to this. Im experiencing the same issue
